name: 🐛 Bug report
description: Report a problem or unexpected behaviour
labels: [bug]
body:
- type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "My problem isn't listed in the [Troubleshooting](https://github.com/vyfor/cord.nvim/wiki/Troubleshooting) section of the wiki"
          required: true
        - label: "I have looked through [existing issues](https://github.com/vyfor/cord.nvim/issues)"
          required: true
        - label: "I am aware of the recent [announcements](https://github.com/vyfor/cord.nvim/discussions/categories/announcements)"
          required: true
  - type: textarea
    attributes:
      label: "Description"
      description: "Explain the issue you are facing. You may include any relevant logs, screenshots, etc. In case the bug is subtle or hard to spot, consider providing additional [logs](https://github.com/vyfor/cord.nvim/wiki/FAQ#logging-for-debugging)."
      value: |
        <!-- describe the problem -->



        <details>
        <summary>Logs (optional)</summary>

        <!-- paste logs inside this block -->

        </details>

    validations:
      required: true
  - type: textarea
    attributes:
      label: "Debug information"
      description: "Output of `:Cord debug copy`"
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Minimal configuration"
      description: "Minimal configuration to reproduce the issue"
      value: |
        <!-- if possible, include steps to reproduce using this minimal config -->

        ```lua
        vim.env.LAZY_STDPATH = '.repro'
        load(vim.fn.system 'curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua')()

        require('lazy.minit').repro {
          spec = {
            {
              'vyfor/cord.nvim',
            },
          },
        }
        ```
    validations:
      required: false
