name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build
      run: |
        rustup default 1.89.0
        cargo build --verbose
